################################################################
# API and dashboard configuration
################################################################
api:
  insecure: true
  dashboard: true
  debug: true

################################################################
# Traefik Logging
################################################################
log:
  level: DEBUG
################################################################
# Traefik Provider
################################################################
providers:
  file:
    filename: "/etc/traefik/dynamic/redirect.yml"
    watch: true